export const CROP_CATEGORIES = {
  WHEAT: 'GRAIN',
  RICE: 'GRAIN',
  MAIZE: 'GRAIN',

  TOMATO: 'VEGETABLE',
  ONION: 'VEGETABLE',
  POTATO: 'VEGETABLE',

  SPINACH: 'LEAFY',
  CORIANDER: 'LEAFY',

  MANGO: 'FRUIT',
  BANANA: 'FRUIT'
};
